- name: Configure Web Server
  hosts: web
  become: yes
  gather_facts: no

  tasks:
    - name: Install nginx
      raw: amazon-linux-extras install nginx1 -y 

    - name: Start nginx
      raw: systemctl start nginx

    - name: Enable nginx
      raw: systemctl enable nginx

    - name: Create index page
      raw: echo "Hello from Ansible 🚀" | tee /usr/share/nginx/html/index.html

